### ISSUE TITLE
Canvas size overflows container size

### ISSUE THREAD

**Issue by noamt** [rastating/pixel.js#10]
Thanks for great a great job on this framework!

I'm following and slightly customizing the Coin Collector example for my own game ([CodeWash](https://github.com/noamt/codewash/tree/master/web)) and I'm seeing an issue where these lines in `pixel.js` :

```javascript
this._canvas.style.width = '100%';
this._canvas.style.height = '100%';
```

Cause my background tiles to cover the complete webpage rather than fill the `game_container` div.
Is there any way to solve this other than comment out these lines?

**Comment by rastating** [comment]
Hey @noamt, thanks for the feedback, I've not done any work on this in a long time but hoping to pick it up again in the upcoming weeks :)

In regards to your problem, you need to set the game container to have a relative position, to do this, in your index.html file, change line 14 from:

```html
<div id="game_container" style="margin: 0 auto; width: 800px; height: 450px;">```
```

To:

```html
<div id="game_container" style="position: relative; margin: 0 auto; width: 800px; height: 450px;">```
```

Hope that helps :)

**Comment by rastating** [comment]
FYI, that's line 14 of the index file in the repository that you linked, the CodeWash one :)

**Comment by noamt** [comment]
Sorry for the n00b question, I'll read up on this. Thanks again!

**Comment by rastating** [comment]
No problem :)
